{
 "title": "Resilience4j",
 "description": "Resilience4j Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "server",
    "label": "Server",
    "query": "label_values(resilience4j_circuitbreaker_state{application=\"$application\"}, server)"
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": "label_values(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\"}, name)"
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": "label_values(resilience4j_retry_calls{application=\"$application\", server=~\"$server\"}, name)"
   },
   {
    "name": "bulkhead_name",
    "label": "Bulkead Name",
    "query": "label_values(resilience4j_bulkhead_available_concurrent_calls{application=\"$application\", server=~\"$server\"}, name)"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=\"closed\"})"
    }
   ]
  },
  {
   "title": "Number of open CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=~\"open|forced_open\"})"
    }
   ]
  },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=\"closed\"})"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Number" }
   ],
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=\"closed\"})",
     "legendFormat": "closed"
    },
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=\"open\"})",
     "legendFormat": "open"
    },
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=\"half_open\"})",
     "legendFormat": "half_open"
    },
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=\"forced_open\"})",
     "legendFormat": "forced_open"
    },
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=\"metrics_only\"})",
     "legendFormat": "metrics_only"
    }
   ]
  },
  {
   "title": "Number of half_open CircuitBreaker",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", state=\"half_open\"})"
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "circuitbreaker_name" },
  {
   "title": "Failure Rate",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "avg(resilience4j_circuitbreaker_failure_rate{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Calls/sec" }
   ],
   "targets": [
    {
     "expr": "avg(rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", kind=\"failed\"}[1m]))",
     "legendFormat": "failed"
    },
    {
     "expr": "avg(rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\", kind=\"successful\"}[1m]))",
     "legendFormat": "successful"
    },
    {
     "expr": "avg(rate(resilience4j_circuitbreaker_calls_seconds_count{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\" ,kind=\"ignored\"}[1m]))",
     "legendFormat": "ignored"
    },
    {
     "expr": "avg(rate(resilience4j_circuitbreaker_not_permitted_calls_total{application=\"$application\", server=~\"$server\", name=~\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "not permitted"
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "repeat": "retry_name" },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 }, "repeat": "bulkhead_name" }
 ]
}