resilience4j.circuitbreaker:
  configs:
    default:
      minimumNumberOfCalls: 5
      failureRateThreshold: 50
      recordExceptions:
        - java.io.IOException
  instances:
    testCircuitBreaker:
      baseConfig: default